{{- if eq .Values.seataServer.mode "cluster" }}
apiVersion: operator.seata.apache.org/v1
kind: SeataServer
metadata:
  name: {{ .Values.seataServer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Service name
  serviceName: {{ .Values.seataServer.service.name }}
  
  # Number of replicas
  replicas: {{ .Values.seataServer.replicas }}
  
  # Container image
  image: {{ .Values.seataServer.image.repository }}:{{ .Values.seataServer.image.tag }}
  imagePullPolicy: {{ .Values.seataServer.image.pullPolicy }}
  
  # Container name
  containerName: seata-server
  
  # Port configuration
  ports:
    consolePort: {{ .Values.seataServer.ports.console }}
    servicePort: {{ .Values.seataServer.ports.service }}
    raftPort: {{ .Values.seataServer.ports.raft }}
  
  # Persistence configuration
  persistence:
    volumeReclaimPolicy: {{ .Values.seataServer.persistence.reclaimPolicy }}
    spec:
      accessModes:
        - {{ .Values.seataServer.persistence.accessMode }}
      {{- if .Values.seataServer.persistence.storageClassName }}
      storageClassName: {{ .Values.seataServer.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.seataServer.persistence.size }}
  
  # Storage configuration
  store:
    resources:
      requests:
        storage: {{ .Values.seataServer.persistence.size }}
  
  # Resource configuration
  resources:
    {{- toYaml .Values.seataServer.resources | nindent 4 }}
  
  # Environment variables
  env:
    {{- include "seata-server.env" . | nindent 4 }}
{{- end }}

