{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secret.password | quote }}
{{- end }}

