#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.seataServer.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ if .Values.seataServer.nodePort.enabled }}{{ .Values.seataServer.nodePort.type }}{{ else }}{{ .Values.seataServer.service.type }}{{ end }}
  selector:
    {{- include "seata-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      port: {{ .Values.seataServer.service.ports.service.port }}
      targetPort: {{ .Values.seataServer.service.ports.service.targetPort }}
      protocol: {{ .Values.seataServer.service.ports.service.protocol }}
      {{- if and .Values.seataServer.nodePort.enabled (eq .Values.seataServer.service.type "NodePort") }}
      nodePort: {{ .Values.seataServer.nodePort.ports.service }}
      {{- end }}
    - name: console
      port: {{ .Values.seataServer.service.ports.console.port }}
      targetPort: {{ .Values.seataServer.service.ports.console.targetPort }}
      protocol: {{ .Values.seataServer.service.ports.console.protocol }}
      {{- if and .Values.seataServer.nodePort.enabled (eq .Values.seataServer.service.type "NodePort") }}
      nodePort: {{ .Values.seataServer.nodePort.ports.console }}
      {{- end }}
    - name: raft
      port: {{ .Values.seataServer.service.ports.raft.port }}
      targetPort: {{ .Values.seataServer.service.ports.raft.targetPort }}
      protocol: {{ .Values.seataServer.service.ports.raft.protocol }}

