#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if and .Values.webhook.enabled (eq .Values.seataServer.mode "cluster") }}
{{- if .Values.webhook.certManager.enabled }}
# Self-signed certificate issuer for webhook
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "seata-server.fullname" . }}-webhook-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  selfSigned: {}

---
# Certificate for webhook TLS
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "seata-server.fullname" . }}-webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  secretName: {{ include "seata-server.fullname" . }}-webhook-certs
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: {{ include "seata-server.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ include "seata-server.fullname" . }}-webhook
    - {{ include "seata-server.fullname" . }}-webhook.{{ .Release.Namespace }}
    - {{ include "seata-server.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "seata-server.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "seata-server.fullname" . }}-webhook-selfsigned-issuer
    kind: Issuer

{{- else }}
# Self-signed certificate (generated manually or via Job)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seata-server.fullname" . }}-webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seata-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
type: kubernetes.io/tls
data:
  {{- if .Values.webhook.tls.crt }}
  tls.crt: {{ .Values.webhook.tls.crt }}
  {{- end }}
  {{- if .Values.webhook.tls.key }}
  tls.key: {{ .Values.webhook.tls.key }}
  {{- end }}

{{- end }}
{{- end }}

